version: '3.9'


services:
  clone_steam:
    build:
      context: ..
      dockerfile: Dockerfile

    ports: 
      - "${API_PORT}:8000"

    volumes:
      - ../app/:/app/

    env_file:
      - ../.env

    depends_on:
      kafka:
        condition: service_healthy

    command: "uvicorn --factory application.main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"